### ISSUE TITLE
Tailwind Preset - Color

### ISSUE THREAD

**Issue by garrettbear** [MetaMask/metamask-design-system#15]
#### **Description**
Develop a Tailwind CSS preset package that includes custom color tokens derived from the design system. This will allow developers to use the same color palette consistently across multiple projects.

#### **Technical Details**
- Extract design tokens related to colors (primary, secondary, etc.) from the design system.
- Create a custom Tailwind CSS preset that extends the default theme with these colors.
- Include documentation on how to use the preset package in projects.
- Add support for light and dark modes if applicable.

#### **Acceptance Criteria**
- Developers can install and use the Tailwind preset to apply design system colors in their projects.
- Colors in the preset match the design tokens exactly.
- Document the process to install and use the preset in different React projects.

#### **References**
- [Tailwind Presets](https://tailwindcss.com/docs/presets)
- Design token libraries and examples.

**Comment by georgewrmarshall** [comment]
Completed in https://github.com/MetaMask/metamask-design-system/pull/41
